// examples/vue-demo/src/App.vue
<script setup lang="ts">
defineProps<{ monitor: { flush(): void } }>()
const runtimeError = () => { throw new Error('Vue demo runtime error') }
const rejectedPromise = () => Promise.reject(new Error('Vue demo rejected promise'))
const changeRoute = () => history.pushState({}, '', `#/profile-${Date.now()}`)
</script>
<template>
  <main><h1>Vue Monitoring Demo</h1><p>Use these controls, then inspect PulseBoard.</p>
    <button @click="runtimeError">Runtime error</button><button @click="rejectedPromise">Rejected promise</button>
    <button @click="fetch('/missing-api')">Failed request</button><button @click="changeRoute">Route change</button>
    <button @click="monitor.flush()">Flush telemetry</button><label>Replay-safe input <input placeholder="Input is masked in replay" /></label>
  </main>
</template>
<style>body { font-family: system-ui; margin: 40px; } button, input { display: block; margin: 12px 0; padding: 8px 12px; }</style>

// examples/react-demo/src/app.tsx
import { useState } from 'react'
import { monitor } from './monitor'

export function App() {
  const [route, setRoute] = useState('home')
  return <main><h1>React Monitoring Demo</h1><p>Use these controls, then inspect PulseBoard.</p>
    <button onClick={() => { throw new Error('React demo runtime error') }}>Runtime error</button>
    <button onClick={() => Promise.reject(new Error('React demo rejected promise'))}>Rejected promise</button>
    <button onClick={() => fetch('/missing-api')}>Failed request</button>
    <button onClick={() => { history.pushState({}, '', `#/${route === 'home' ? 'profile' : 'home'}`); setRoute(route === 'home' ? 'profile' : 'home') }}>Route change</button>
    <button onClick={() => monitor.flush()}>Flush telemetry</button>
    <label>Replay-safe input <input placeholder="Input is masked in replay" /></label>
    <p>Current route: {route}</p>
  </main>
}
